"""
7_debug_inference.py
Trace the exact token stream generated by the model to diagnose Alignment Loss.
"""
import os
import torch
import numpy as np
from src.model import TRM, TRMConfig

DATA_DIR = "data"
CHECKPOINT_PATH = "checkpoints/ckpt_350.pt" 
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

config = TRMConfig(
    vocab_size=8192, dim=192, n_layers=3, n_recurrence=2,  
    n_heads=6, n_kv_heads=2, max_seq_len=2048, dropout=0.1
)

def main():
    print("🔹 Debugging Generation Trace...")
    
    # 1. Load Bins & Model
    bins = np.load(os.path.join(DATA_DIR, "bins.npy"), allow_pickle=True).item()
    log_ret_bins = bins['log_ret']
    
    OFFSET_VOLAT = 31
    OFFSET_VOL = OFFSET_VOLAT + len(bins['volat_lag']) + 1
    OFFSET_RET = OFFSET_VOL + len(bins['vol_lag']) + 1
    
    print(f"OFFSET_RET: {OFFSET_RET}")
    zero_idx = np.abs(np.array(log_ret_bins)).argmin()
    ZERO_TOKEN_ID = OFFSET_RET + zero_idx
    print(f"ZERO_TOKEN_ID: {ZERO_TOKEN_ID}")
    
    model = TRM(config).to(DEVICE)
    model.load_state_dict(torch.load(CHECKPOINT_PATH, map_location=DEVICE))
    model.eval()

    # 2. Get Input (Aligned)
    filename = os.path.join(DATA_DIR, 'val.bin')
    data = np.memmap(filename, dtype=np.uint16, mode='r')
    
    # Take 50 steps (250 tokens). Ends with R.
    ctx_len = 250
    ctx_tokens = torch.from_numpy(data[:ctx_len].astype(np.int64)).unsqueeze(0).to(DEVICE)
    
    print(f"\n--- Starting Generation Trace (10 Steps) ---")
    print(f"Initial Context Ends With: {ctx_tokens[0, -5:].tolist()}")
    
    curr_idx = ctx_tokens
    
    # Generate 100 tokens (20 steps)
    for i in range(100):
        # Forward
        logits, _ = model(curr_idx)
        last_logits = logits[:, -1, :]
        
        # Greedy (Argmax) or Sample?
        # Let's use Top 1 Sample to match inference
        probs = torch.nn.functional.softmax(last_logits, dim=-1)
        next_token = torch.multinomial(probs, num_samples=1)
        
        tok_id = next_token.item()
        
        # Identify Type
        t_type = "?"
        if tok_id < 7: t_type = "DOW"
        elif tok_id < 31: t_type = "HOUR"
        elif tok_id < OFFSET_VOL: t_type = "VOLAT"
        elif tok_id < OFFSET_RET: t_type = "VOL"
        else:
            t_type = "RET"
            val = log_ret_bins[tok_id - OFFSET_RET] if (tok_id - OFFSET_RET) < len(log_ret_bins) else "ERR"
            if isinstance(val, float): t_type += f"({val:.4f})"
            
        print(f"Step {i+1}: Generated {tok_id:<5} [{t_type}]")
        
        curr_idx = torch.cat((curr_idx, next_token), dim=1)

if __name__ == "__main__":
    main()
